a="""
a2ps                                     librasterlite
a52dec                                   libraw
aacgain                                  librcsc
aalib                                    librdkafka
aamath                                   libre
aardvark_shell_utils                     libreadline-java
abcde                                    librealsense
abcl                                     librem
abcm2ps                                  libreplaygain
abcmidi                                  libresample
abduco                                   libressl
abnfgen                                  librest
abook                                    librevenge
abseil                                   librsvg
abuse                                    librsync
abyss                                    librtlsdr
ace                                      librttopo
aces_container                           libsamplerate
ack                                      libsass
acl2                                     libsbol
acme                                     libscrypt
acmetool                                 libseccomp
acpica                                   libsecret
act                                      libserdes
activemq                                 libserialport
activemq-cpp                             libshout
adios2                                   libsigc++
admesh                                   libsigc++@2
adns                                     libsignal-protocol-c
adplug                                   libsigsegv
adr-tools                                libsixel
advancecomp                              libslax
advancemame                              libslirp
advancemenu                              libsm
advancescan                              libsmf
adwaita-icon-theme                       libsmi
aerc                                     libsndfile
aescrypt                                 libsodium
aescrypt-packetizer                      libsoundio
aespipe                                  libsoup
afflib                                   libsoxr
afio                                     libspatialite
afl-fuzz                                 libspectre
afsctool                                 libspectrum
aften                                    libspiro
afuse                                    libspnav
agda                                     libspng
agedu                                    libsquish
aggregate                                libssh
aha                                      libssh2
ahcpd                                    libstatgrab
ahoy                                     libstfl
aida-header                              libstrophe
aide                                     libstxxl
aircrack-ng                              libsvg
airshare                                 libsvg-cairo
airspy                                   libsvm
akamai                                   libswiften
akka                                     libswiftnav
alac                                     libtar
aldo                                     libtasn1
alexjs                                   libtcod
algernon                                 libtecla
algol68g                                 libtensorflow
align                                    libtensorflow@1
aliyun-cli                               libtermkey
allegro                                  libtextcat
allure                                   libtiff
allureofthestars                         libtins
alluxio                                  libtirpc
alot                                     libtomcrypt
alp                                      libtommath
alpine                                   libtool
alsa-lib                                 libtorch
alure                                    libtorrent-rakshasa
amap                                     libtorrent-rasterbar
amazon-ecs-cli                           libtrace
amdatu-bootstrap                         libtrng
ammonite-repl                            libu2f-host
amp                                      libu2f-server
ampl-mp                                  libucl
amqp-cpp                                 libuecc
amtk                                     libuninameslist
amtterm                                  libunistring
analog                                   libunwind-headers
angband                                  libupnp
angle-grinder                            libusb
angular-cli                              libusb-compat
anime-downloader                         libusbmuxd
anjuta                                   libusrsctp
annie                                    libuv
ansible                                  libuvc
ansible-cmdb                             libva
ansible-lint                             libvbucket
ansible@2.8                              libvdpau
ansifilter                               libvidstab
ansiweather                              libvirt
ant                                      libvirt-glib
ant-contrib                              libvisio
ant@1.9                                  libvmaf
antibody                                 libvnc
antigen                                  libvncserver
antiword                                 libvo-aacenc
antlr                                    libvoikko
antlr4-cpp-runtime                       libvorbis
antlr@2                                  libvpx
anttweakbar                              libvterm
anycable-go                              libwandevent
anyenv                                   libwbxml
aoeui                                    libwebm
aom                                      libwebsockets
apache-archiva                           libwmf
apache-arrow                             libwpd
apache-arrow-glib                        libwpg
apache-brooklyn-cli                      libwps
apache-ctakes                            libx11
apache-drill                             libxau
apache-flink                             libxaw
apache-forrest                           libxaw3d
apache-geode                             libxc
apache-opennlp                           libxcb
apache-spark                             libxcomposite
apachetop                                libxcursor
apcupsd                                  libxdamage
ape                                      libxdg-basedir
apgdiff                                  libxdiff
apib                                     libxdmcp
apibuilder-cli                           libxext
apidoc                                   libxfixes
apktool                                  libxfont
apm-bash-completion                      libxft
apng2gif                                 libxi
apngasm                                  libxinerama
apollo                                   libxkbcommon
apollo-cli                               libxkbfile
app-engine-java                          libxlsxwriter
app-engine-python                        libxmi
apparix                                  libxml++
appium                                   libxml++3
appledoc                                 libxml++@4
appscale-tools                           libxml++@5
appstream-glib                           libxml2
apr                                      libxmlsec1
apr-util                                 libxmp
apt-dater                                libxmp-lite
aptly                                    libxmu

"""